---
name: Deploy
on:
  workflow_dispatch:
    inputs:
      lambda:
        description: 'Lambda Name'
        required: true
        default: 'indexing'
env:
  REGISTRY: ghcr.io
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js Current
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Prepare deployment
        run: |
          echo IMAGE_REPOSITORY=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
          echo PACKAGE_VERSION=$(cat package.json | jq -r '.version') >> $GITHUB_ENV
          echo BUILD_DATE=$(date +%Y%m%d.%H%M) >> $GITHUB_ENV
          echo LAMBDA=${{ github.event.inputs.lambda }} >> $GITHUB_ENV
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Deploy Lambda
        run: |
          npm run deploy
        env:
          LAMBDA: ${{ env.LAMBDA }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPOSITORY }}
